### ISSUE TITLE
smoderp1d process in async mode fails with unicodeerror

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#111]
Deploy smoderp wps server, see `bin\wps\README.md`.

```
cd bin/wps
docker-compose up
```

Running smoderp1d process in sync mode works:

```
python3 request-template.py --template request-smoderp1d.xml > /tmp/request.xml && wget --post-file /tmp/request.xml 'http://localhost:8080/services/wps?' -O -
```

After enabling async mode, [async.txt](https://github.com/storm-fsv-cvut/smoderp2d/files/5742235/async.txt):

```
patch -p3 < async.txt
```

process fails with

```
smoderp_wps_demo_1 | Traceback (most recent call last):
smoderp_wps_demo_1 |   File "/usr/local/lib/python3.6/dist-packages/pywps/response/execute.py", line 97, in _update_status_file
smoderp_wps_demo_1 |     data_format=FORMATS.XML)
smoderp_wps_demo_1 |   File "/usr/local/lib/python3.6/dist-packages/pywps/inout/storage/file.py", line 126, in write
smoderp_wps_demo_1 |     file.write(data)
smoderp_wps_demo_1 | UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 1377: ordinal not in range(128)
smoderp_wps_demo_1 | 
smoderp_wps_demo_1 | During handling of the above exception, another exception occurred:
smoderp_wps_demo_1 | 
smoderp_wps_demo_1 | Traceback (most recent call last):
smoderp_wps_demo_1 |   File "/usr/local/lib/python3.6/dist-packages/pywps/app/Process.py", line 254, in _run_process
smoderp_wps_demo_1 |     wps_response._update_status(WPS_STATUS.SUCCEEDED, 'PyWPS Process {} finished'.format(self.title), 100)
smoderp_wps_demo_1 |   File "/usr/local/lib/python3.6/dist-packages/pywps/response/execute.py", line 63, in _update_status
smoderp_wps_demo_1 |     self._update_status_file()
smoderp_wps_demo_1 |   File "/usr/local/lib/python3.6/dist-packages/pywps/response/execute.py", line 99, in _update_status_file
smoderp_wps_demo_1 |     raise NoApplicableCode('Writing Response Document failed with : {}'.format(e))
smoderp_wps_demo_1 | pywps.exceptions.NoApplicableCode: 400 NoApplicableCode: Writing Response Document failed with : 'ascii' codec can't encode character '\ufeff' in position 1377: ordinal not in range(128)
```

**Comment by landam** [comment]
PyWPS can be fixed by [file.txt](https://github.com/storm-fsv-cvut/smoderp2d/files/5742244/file.txt)

```
cp file.txt log/
docker-compose exec smoderp_wps bash
patch -p0 < /var/log/pywps/file.txt
exit
```

Restart docker container and run process again. Now it works.

**Comment by landam** [comment]
One strange thing: pywps is storing some inputs (those in CSV with BOM):

```
 file log/x/input
log/x/input: UTF-8 Unicode (with BOM) text
```

**Comment by landam** [comment]
Another strange thing: when running process in async mode first two lines of output CSV are merged.

![Screenshot from 2020-12-25 18-48-20](https://user-images.githubusercontent.com/5683186/103139948-28715000-46e2-11eb-9859-c16908cd5535.png)

But not merge in sync mode:

```
                    <wps:ComplexData mimeType="text/csv" encoding="" schema=""><![CDATA[length[m],soil_vegFID,maximalSurfaceFlow[m3/s],totalRunoff[m3],maximalSurfaceRunoffVelocity[m/s],maximalTangentialStress[Pa],rillRunoff[Y/N]
1.0047619,HXGEO,2.828914373790249e-05,0.0,0.13555176296624516,0.1616611778504513,0
1.0047619,HXGEO,5.65757029586212e-05,0.0,0.17505214051547188,0.2503533814180063,0
```

**Comment by landam** [comment]
The problem appears only in async mode since the output XML contains also input files (which encodes PyWPS with BOM), see https://github.com/storm-fsv-cvut/smoderp2d/issues/111#issuecomment-751276016.

Original request doesn't contain BOM:

```
file /tmp/request.xml 
/tmp/request.xml: XML 1.0 document, UTF-8 Unicode text, with very long lines
```

**Comment by landam** [comment]
Comment above corrected, opposite is a true:

```
grep -r $'\xEF\xBB\xBF' /tmp/request.xml 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <wps:ComplexData mimeType="text/csv"><![CDATA[﻿vodorovny prumet stahu[m];prevyseni[m];povrch;puda;sklon
        <wps:ComplexData mimeType="text/csv"><![CDATA[﻿soilveg;k;s;n;pi;ppl;ret;b;x;y;tau;v
```

**Comment by landam** [comment]
Ops, problem is the input data:

```
file ../../tests/data/nogis/data1D.csv 
../../tests/data/nogis/data1D.csv: UTF-8 Unicode (with BOM) text, with CRLF line terminators
```
