### ISSUE TITLE
smoderp nogis failing in issue_119_cleanup_cumulative_max

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#121]
```
smoderp_wps_demo_1 | Traceback (most recent call last):
smoderp_wps_demo_1 |   File "/usr/local/lib/python3.6/dist-packages/pywps/app/Process.py", line 249, in _run_process
smoderp_wps_demo_1 |     self.handler(wps_request, wps_response)  # the user must update the wps_response.
smoderp_wps_demo_1 |   File "/opt/pywps/processes/smoderp1d.py", line 93, in _handler
smoderp_wps_demo_1 |     runner.run()
smoderp_wps_demo_1 |   File "/opt/smoderp2d/smoderp2d/__init__.py", line 93, in run
smoderp_wps_demo_1 |     from smoderp2d.runoff import Runoff
smoderp_wps_demo_1 |   File "/opt/smoderp2d/smoderp2d/runoff.py", line 23, in <module>
smoderp_wps_demo_1 |     from smoderp2d.core.cumulative_max import Cumulative
smoderp_wps_demo_1 |   File "/opt/smoderp2d/smoderp2d/core/cumulative_max.py", line 102
smoderp_wps_demo_1 |     'h_sheet_tot'      : CumulativeData('control', 'mWLevelsheet_m'),  # 4

```

**Comment by jerabekjak** [comment]
Is there aby error description?

**Comment by landam** [comment]
@jerabekjak Thanks for quick fix
