### ISSUE TITLE
QGIS plugin crashes

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#155]
I tried to run the QGIS plugin, but it crashes for me. Or am I supposed to create the location on my own before running the plugin?

```
2023-04-30T23:03:26     WARNING    Traceback (most recent call last):
              File "/home/ondrej/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/smoderp_2D_dockwidget.py", line 143, in OnRunButton
              runner = QGISRunner()
              ^^^^^^^^^^^^
              File "/home/ondrej/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/../../../smoderp2d/__init__.py", line 138, in __init__
              gsetup.init(os.environ['GISBASE'], gisdb, location, 'PERMANENT')
              File "/usr/lib/grass82/etc/python/grass/script/setup.py", line 326, in init
              raise ValueError(
             ValueError: Mapset /tmp/grassdata/256caa8a18d5f01293d23c8dcbde4ee2 is not valid: is not a valid GRASS Location because PERMANENT Mapset is missing
```

**Comment by landam** [comment]
You have to execute GRASS binary (see https://github.com/OSGeo/grass/issues/1987) to create new location.

**Comment by pesekon2** [comment]
```
> /tmp/grassdata/6cc55d5f14be6fbcc1c86c13820b463a/PERMANENT/
DEFAULT_WIND  MYNAME  PROJ_INFO  PROJ_SRID  PROJ_UNITS  PROJ_WKT  sqlite  VAR  WIND
```

```
> gsetup.init('/home/ondrej/workspace/grass/dist.x86_64-pc-linux-gnu', '/tmp/grassdata', '6cc55d5f14be6fbcc1c86c13820b463a', 'PERMANENT')
ValueError: Mapset /tmp/grassdata/6cc55d5f14be6fbcc1c86c13820b463a is not valid: is not a valid GRASS Location because PERMANENT Mapset is missing
```

**Comment by landam** [comment]
https://grass.osgeo.org/grass82/manuals/libpython/_modules/script/setup.html: 

try

```
gsetup.init('/tmp/grassdata', '6cc55d5f14be6fbcc1c86c13820b463a', 'PERMANENT', grass_path='/home/ondrej/workspace/grass/dist.x86_64-pc-linux-gnu')
```
