### ISSUE TITLE
Computation in ArcGIS fails 

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#169]
```py
C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: divide by zero encountered in true_divide
  infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: invalid value encountered in true_divide
  infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
Traceback (most recent call last):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\test_arcgis.py", line 27, in <module>
    perform_dpre_ref_test(ArcGisRunner, dpre_params, dataprep_only=False)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\dpre_utils.py", line 85, in perform_dpre_ref_test
    runner.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\__init__.py", line 101, in run
    runoff.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\runoff.py", line 361, in run
    self.surface.stream_reach_outflow(self.delta_t)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\core\stream.py", line 106, in stream_reach_outflow
    r.outflow_method(r, dt)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\stream_functions\stream_f.py", line 162, in triangle
    he = compute_h(A=Ve / reach.length, m=reach.m, b=B)  # funkce pouzita pro lichobeznik  ____
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\stream_functions\stream_f.py", line 40, in compute_h
    while feval(h_pre) > err:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by pesekon2** [comment]
@landam: Could you please check it again in branch [fix_stream_f_compute_h](https://github.com/storm-fsv-cvut/smoderp2d/tree/fix_stream_f_compute_h)?
