### ISSUE TITLE
ArcGIS provider fails with "A two or three dimensional NumPy array is required"

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#179]
```
Traceback (most recent call last):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\test_arcgis.py", line 27, in <module>
    perform_dpre_ref_test(ArcGisRunner, dpre_params, dataprep_only=False)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\dpre_utils.py", line 86, in perform_dpre_ref_test
    runner.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\__init__.py", line 105, in run
    runoff.save_output()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\runoff.py", line 441, in save_output
    self.provider.postprocessing(self.cumulative, self.surface.arr,
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\base\__init__.py", line 448, in postprocessing
    self.storage.write_raster(
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\arcgis\__init__.py", line 75, in write_raster
    raster = arcpy.NumPyArrayToRaster(
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 2457, in NumPyArrayToRaster
    return _NumPyArrayToRaster(*args, **kwargs)
ValueError: Argument in_array: A two or three dimensional NumPy array is required.
```

**Comment by landam** [comment]
```
<class 'numpy.ma.core.MaskedArray'>
[[-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]
 ...
 [-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]]
```

-> mask replaced by NoDataValue

**Comment by landam** [comment]
@pesekon2 base.BaseWritter should do this conversion for argis.ArcGisWritter/grass.GrassWritter.

**Comment by pesekon2** [comment]
@landam: Do you have any idea if this is still a valid issue?

**Comment by landam** [comment]
Not able to reproduce it. Closing.
