### ISSUE TITLE
points_in_boundery_cells

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#277]
Qgis ignore points on boundary layer, why? Value in this cells are corect
AQ try use it, but the exeptions are in lines 

![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/4d52b1c1-230a-4544-8146-beafa9037045)

**Comment by landam** [comment]
It also applies to ArcGIS. 

```
Traceback (most recent call last):
  File "<string>", line 238, in execute
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\__init__.py", line 100, in run
    self._provider.load()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\providers\base\__init__.py", line 308, in load
    data = self._load_dpre()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\providers\arcgis\__init__.py", line 109, in _load_dpre
    return prep.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\providers\base\data_preparation.py", line 566, in run
    self.data['array_points'] = self._get_points_location(
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\providers\arcgis\data_preparation.py", line 301, in _get_points_location
    if self._get_points_dem_coords(x, y):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\providers\base\data_preparation.py", line 716, in _get_points_dem_coords
    self.data['mat_dem'][r+1][c] != nv and \
IndexError: index 17 is out of bounds for axis 0 with size 17

Failed to execute (SMODERP2D).
```
