### ISSUE TITLE
QGIS repeated computation fails on Windows

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#278]
Steps to reproduce:

1. Run computation -> success
2. Run computation second time -> failure

```py
2023-10-26T16:57:12     WARNING    Traceback (most recent call last):
              File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\qgis\smoderp2d-plugin\smoderp_2D_dockwidget.py", line 75, in run
              runner.import_data(self.input_maps)
              File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\qgis\smoderp2d-plugin\..\..\..\smoderp2d\__init__.py", line 216, in import_data
              Module(
              File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\pygrass\modules\interface\module.py", line 610, in __init__
              self.__call__(*args, **kargs)
              File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\pygrass\modules\interface\module.py", line 634, in __call__
              return self.run()
              File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\pygrass\modules\interface\module.py", line 823, in run
              self.wait()
              File "C:\OSGeo4W\apps\grass\grass83\etc\python\grass\pygrass\modules\interface\module.py", line 844, in wait
              raise CalledModuleError(
             grass.exceptions.CalledModuleError: Module run `v.import input=C:/Users/martin/Documents/GitHub/smoderp2d/tests/data/soils.shp extent=input snap=-1.0 output=soil` ended with an error.
             The subprocess ended with a non-zero return code: 1. See errors above the traceback or in the error output.
```

**Comment by landam** [comment]
Possible reason:

```
WARNING: Unable to open datum table file
/etc/proj/datum.table>pps\grass\grass83
WARNING: Unable to open ellipsoid table file
/etc/proj/ellipse.table>s\grass\grass83
WARNING: Unable to open ellipsoid table file
```

**Comment by landam** [comment]
From very strange reason on the second run:

```
D2/5: dbDbmscap(): opendir [C:\OSGeo4W\apps\grass\grass83
\driver\db\]
```
