### ISSUE TITLE
ArcGIS: cannot remove temporary data

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#349]
Run ArcGIS toolbox with `Generated also temporary data` unchecked:

```py
Traceback (most recent call last):
  File "<string>", line 258, in execute
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\runners\base.py", line 93, in run
    runoff.save_output()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\runoff.py", line 448, in save_output
    self.provider.postprocessing(self.cumulative, self.surface.arr,
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\providers\base\__init__.py", line 652, in postprocessing
    self._postprocessing()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\..\..\smoderp2d\providers\arcgis\__init__.py", line 125, in _postprocessing
    arcpy.Delete_management(os.path.join(data_dir, "data.gdb"))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 7419, in Delete
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 7416, in Delete
    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000601: Cannot delete C:\Users\martin\Downloads\rain_sim\temp\data.gdb.  May be locked by another application.
Failed to execute (Delete).


Failed to execute (SMODERP2D).
```

**Comment by landam** [comment]
Still relevant
