### ISSUE TITLE
ArcGIS 2.4 fails with test data

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#57]
Fresh installation of Windows (VM), ArcGIS Pro 2.4. Running toolbox with test data crashes with

```
Prepare points for hydrographs...
Failed script SMODERP2D...
 Traceback (most recent call last):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\start-smoderp2d.py", line 13, in <module>
    sys.exit(runner.run())
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\__init__.py", line 66, in run
    self._provider.load()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\base\__init__.py", line 144, in load
    data = self._load_dpre()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\arcgis\__init__.py", line 55, in _load_dpre
    return prep.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\base\data_preparation.py", line 96, in run
    self._get_array_points()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\arcgis\data_preparation.py", line 349, in _get_array_points
    pnt.X, pnt.Y, fid, i
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\..\smoderp2d\providers\base\data_preparation.py", line 347, in _get_array_points_
    self.data['array_points'][i][0] = fid
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Tested on other Windows computer with ArcGIS 10.5, here it works (with same test data from git). It must be something new with 2.4, in ArcGIS Pro 2.3 it worked ASAIR.

Mystery. @kavkapet @jerabekjak Any idea?

**Comment by landam** [comment]
Unable to reproduce this issue with latest master.

![VirtualBox_Windows 10 (ArcGIS Pro)_11_11_2019_15_55_30](https://user-images.githubusercontent.com/5683186/68596761-085ddd80-049c-11ea-8829-2dce299acda2.png)

**Comment by landam** [comment]
Unfortunately the issue is still relevant

**Comment by landam** [comment]
Unable to reproduce now. Closing.
