### ISSUE TITLE
test.ini fails with NotImplementedError

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#71]
```
./bin/start-smoderp2d.py --typecomp roff --indata tests/test.ini
```

currently fails with

```
Traceback (most recent call last):
  File "./bin/start-smoderp2d.py", line 20, in <module>
    sys.exit(runner.run())
  File "./bin/../smoderp2d/__init__.py", line 75, in run
    from smoderp2d.runoff import Runoff
  File "./bin/../smoderp2d/runoff.py", line 19, in <module>
    from smoderp2d.core.surface import Surface
  File "./bin/../smoderp2d/core/surface.py", line 9, in <module>
    from smoderp2d.core.stream import Stream
  File "./bin/../smoderp2d/core/stream.py", line 1, in <module>
    from smoderp2d.stream_functions import stream_f
  File "./bin/../smoderp2d/stream_functions/stream_f.py", line 194
    raise NotImplementedError('Parabola shaped stream reach is not implemented
                                                                             ^
SyntaxError: EOL while scanning string literal
```

**Comment by jerabekjak** [comment]
@landam bug fixed. closing issue.

**Comment by landam** [comment]
@jerabekjak Thanks for quick fix!
