### ISSUE TITLE
test fails in master

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#87]
```
python3 ./bin/start-smoderp2d.py --indata tests/test.ini --typecomp roff
...
2020-11-24 14:36:24,890 - SMODERP2D - INFO - Stream: ON - [stream:66]
Traceback (most recent call last):
  File "./bin/start-smoderp2d.py", line 20, in <module>
    sys.exit(runner.run())
  File "./bin/../smoderp2d/__init__.py", line 80, in run
    runoff = Runoff(self._provider)
  File "./bin/../smoderp2d/runoff.py", line 150, in __init__
    self.surface = Surface()
  File "./bin/../smoderp2d/core/surface.py", line 89, in __init__
    Stream.__init__(self)
  File "./bin/../smoderp2d/core/stream.py", line 69, in __init__
    self.nReaches = len(self.streams['fid'])
TypeError: list indices must be integers or slices, not str
```

Any idea @jerabekjak ?

**Comment by jerabekjak** [comment]
@landam 
in tests/test.ini change a line 55
 49 # type of processes involved
 50 # default si 3
 51 # 0 - sheet runoff
 52 # 1 - sheet and rill runoff 
 53 # 2 - sheet, rill and subsurface runoff
 54 # 3 - sheet, rill and stream runoff
 55 typecomp: 3 -> typecomp: 1

**Comment by jerabekjak** [comment]
The problem is that typecomp 3 means that the model expects vector streem data. But, in the 44 indata: tests/data/nucice.save file the vector data of streams missing.
